<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class TestCollection extends JsonResource
{

    public function toArray($request)
    {
        //return parent::toArray($request); // TODO: Change the autogenerated stub

        return ['test' => 'coucou'];
    }
}